//
// AaguidDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AaguidDetails: Sendable, Codable, ParameterConvertible, Hashable {

    public var name: String
    public var iconLight: String
    public var iconDark: String

    public init(name: String, iconLight: String, iconDark: String) {
        self.name = name
        self.iconLight = iconLight
        self.iconDark = iconDark
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case iconLight
        case iconDark
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(iconLight, forKey: .iconLight)
        try container.encode(iconDark, forKey: .iconDark)
    }
}

