//
// AppendCompletionType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum AppendCompletionType: String, Sendable, Codable, CaseIterable {
    case auto = "auto"
    case conditional = "conditional"
    case manual = "manual"
    case manualRetry = "manual-retry"
}
