//
// AppType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Application type */
public enum AppType: String, Sendable, Codable, CaseIterable {
    case empty = "empty"
    case web = "web"
    case native = "native"
}
