//
// AuthMethod.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Authentication methods */
public enum AuthMethod: String, Sendable, Codable, CaseIterable {
    case email = "email"
    case phoneNumber = "phone_number"
    case webauthn = "webauthn"
    case password = "password"
}
