//
// AuthType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum AuthType: String, Sendable, Codable, CaseIterable {
    case signup = "signup"
    case login = "login"
}
