//
// BlockType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum BlockType: String, Sendable, Codable, CaseIterable {
    case signupInit = "signup-init"
    case passkeyAppend = "passkey-append"
    case phoneVerify = "phone-verify"
    case emailVerify = "email-verify"
    case passkeyAppended = "passkey-appended"
    case completed = "completed"
    case socialVerify = "social-verify"
    case loginInit = "login-init"
    case passkeyVerify = "passkey-verify"
    case conditionalUiCompleted = "conditional-ui-completed"
    case postSignupEmailVerify = "post-signup-email-verify"
    case passkeyAppendAfterHybrid = "passkey-append-after-hybrid"
}
