//
// ClientStateMeta.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ClientStateMeta: Sendable, Codable, ParameterConvertible, Hashable {

    public enum Source: String, Sendable, Codable, CaseIterable {
        case ls = "ls"
        case url = "url"
        case native = "native"
    }
    public var ts: Int64
    public var source: Source

    public init(ts: Int64, source: Source) {
        self.ts = ts
        self.source = source
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ts
        case source
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ts, forKey: .ts)
        try container.encode(source, forKey: .source)
    }
}

