//
// ClientInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ClientInfo: Sendable, Codable, ParameterConvertible, Hashable {

    /** client's IP address */
    public var remoteAddress: String
    /** client's User Agent */
    public var userAgent: String

    public init(remoteAddress: String, userAgent: String) {
        self.remoteAddress = remoteAddress
        self.userAgent = userAgent
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case remoteAddress
        case userAgent
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(remoteAddress, forKey: .remoteAddress)
        try container.encode(userAgent, forKey: .userAgent)
    }
}

