//
// ConnectLoginStartRsp.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ConnectLoginStartRsp: Sendable, Codable, ParameterConvertible, Hashable {

    public var assertionOptions: String
    public var isCDA: Bool

    public init(assertionOptions: String, isCDA: Bool) {
        self.assertionOptions = assertionOptions
        self.isCDA = isCDA
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case assertionOptions
        case isCDA
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(assertionOptions, forKey: .assertionOptions)
        try container.encode(isCDA, forKey: .isCDA)
    }
}

