//
// ConnectLoginStartReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ConnectLoginStartReq: Sendable, Codable, ParameterConvertible, Hashable {

    public enum Source: String, Sendable, Codable, CaseIterable {
        case oneTap = "one-tap"
        case textField = "text-field"
        case errorSoft = "error-soft"
        case errorHard = "error-hard"
    }
    public var identifier: String
    public var source: Source
    public var loadedMs: Int64

    public init(identifier: String, source: Source, loadedMs: Int64) {
        self.identifier = identifier
        self.source = source
        self.loadedMs = loadedMs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case identifier
        case source
        case loadedMs
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(identifier, forKey: .identifier)
        try container.encode(source, forKey: .source)
        try container.encode(loadedMs, forKey: .loadedMs)
    }
}

