//
// ConnectAppendStartRsp.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ConnectAppendStartRsp: Sendable, Codable, ParameterConvertible, Hashable {

    public enum Variant: String, Sendable, Codable, CaseIterable {
        case _default = "default"
        case afterHybrid = "after-hybrid"
        case afterError = "after-error"
    }
    public var attestationOptions: String
    public var variant: Variant

    public init(attestationOptions: String, variant: Variant) {
        self.attestationOptions = attestationOptions
        self.variant = variant
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case attestationOptions
        case variant
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(attestationOptions, forKey: .attestationOptions)
        try container.encode(variant, forKey: .variant)
    }
}

