//
// ConnectLoginFinishReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ConnectLoginFinishReq: Sendable, Codable, ParameterConvertible, Hashable {

    public var isConditionalUI: Bool
    public var assertionResponse: String
    public var loadedMs: Int64?

    public init(isConditionalUI: Bool, assertionResponse: String, loadedMs: Int64? = nil) {
        self.isConditionalUI = isConditionalUI
        self.assertionResponse = assertionResponse
        self.loadedMs = loadedMs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isConditionalUI
        case assertionResponse
        case loadedMs
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(isConditionalUI, forKey: .isConditionalUI)
        try container.encode(assertionResponse, forKey: .assertionResponse)
        try container.encodeIfPresent(loadedMs, forKey: .loadedMs)
    }
}

