//
// ConnectLoginFinishReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ConnectLoginFinishReq: Sendable, Codable, ParameterConvertible, Hashable {

    public var isConditionalUI: Bool
    public var assertionResponse: String

    public init(isConditionalUI: Bool, assertionResponse: String) {
        self.isConditionalUI = isConditionalUI
        self.assertionResponse = assertionResponse
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isConditionalUI
        case assertionResponse
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(isConditionalUI, forKey: .isConditionalUI)
        try container.encode(assertionResponse, forKey: .assertionResponse)
    }
}

