//
// ConnectLoginFinishRsp.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ConnectLoginFinishRsp: Sendable, Codable, ParameterConvertible, Hashable {

    public var passkeyOperation: PasskeyOperation
    public var session: String

    public init(passkeyOperation: PasskeyOperation, session: String) {
        self.passkeyOperation = passkeyOperation
        self.session = session
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case passkeyOperation
        case session
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(passkeyOperation, forKey: .passkeyOperation)
        try container.encode(session, forKey: .session)
    }
}

