//
// ConnectLoginFinishRsp.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ConnectLoginFinishRsp: Sendable, Codable, ParameterConvertible, Hashable {

    public var passkeyOperation: PasskeyOperation?
    public var session: String
    public var signedPasskeyData: String
    public var fallbackOperationError: FallbackOperationError?

    public init(passkeyOperation: PasskeyOperation? = nil, session: String, signedPasskeyData: String, fallbackOperationError: FallbackOperationError? = nil) {
        self.passkeyOperation = passkeyOperation
        self.session = session
        self.signedPasskeyData = signedPasskeyData
        self.fallbackOperationError = fallbackOperationError
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case passkeyOperation
        case session
        case signedPasskeyData
        case fallbackOperationError
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(passkeyOperation, forKey: .passkeyOperation)
        try container.encode(session, forKey: .session)
        try container.encode(signedPasskeyData, forKey: .signedPasskeyData)
        try container.encodeIfPresent(fallbackOperationError, forKey: .fallbackOperationError)
    }
}

