//
// ConnectAppendStartReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ConnectAppendStartReq: Sendable, Codable, ParameterConvertible, Hashable {

    public var appendTokenValue: String
    public var forcePasskeyAppend: Bool?
    public var loadedMs: Int64

    public init(appendTokenValue: String, forcePasskeyAppend: Bool? = nil, loadedMs: Int64) {
        self.appendTokenValue = appendTokenValue
        self.forcePasskeyAppend = forcePasskeyAppend
        self.loadedMs = loadedMs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case appendTokenValue
        case forcePasskeyAppend
        case loadedMs
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(appendTokenValue, forKey: .appendTokenValue)
        try container.encodeIfPresent(forcePasskeyAppend, forKey: .forcePasskeyAppend)
        try container.encode(loadedMs, forKey: .loadedMs)
    }
}

