//
// ConnectManageInitRsp.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ConnectManageInitRsp: Sendable, Codable, ParameterConvertible, Hashable {

    public var processID: String
    public var newClientEnvHandle: String?
    public var expiresAt: Int
    public var frontendApiUrl: String
    public var manageAllowed: Bool
    public var flags: [String: String]

    public init(processID: String, newClientEnvHandle: String? = nil, expiresAt: Int, frontendApiUrl: String, manageAllowed: Bool, flags: [String: String]) {
        self.processID = processID
        self.newClientEnvHandle = newClientEnvHandle
        self.expiresAt = expiresAt
        self.frontendApiUrl = frontendApiUrl
        self.manageAllowed = manageAllowed
        self.flags = flags
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case processID
        case newClientEnvHandle
        case expiresAt
        case frontendApiUrl
        case manageAllowed
        case flags
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(processID, forKey: .processID)
        try container.encodeIfPresent(newClientEnvHandle, forKey: .newClientEnvHandle)
        try container.encode(expiresAt, forKey: .expiresAt)
        try container.encode(frontendApiUrl, forKey: .frontendApiUrl)
        try container.encode(manageAllowed, forKey: .manageAllowed)
        try container.encode(flags, forKey: .flags)
    }
}

