//
// ConnectManageListRsp.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ConnectManageListRsp: Sendable, Codable, ParameterConvertible, Hashable {

    public var passkeys: [Passkey]

    public init(passkeys: [Passkey]) {
        self.passkeys = passkeys
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case passkeys
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(passkeys, forKey: .passkeys)
    }
}

