//
// ConnectProcessClearReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ConnectProcessClearReq: Sendable, Codable, ParameterConvertible, Hashable {

    public var processId: String

    public init(processId: String) {
        self.processId = processId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case processId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(processId, forKey: .processId)
    }
}

