//
// ConnectEventCreateReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ConnectEventCreateReq: Sendable, Codable, ParameterConvertible, Hashable {

    public var eventType: PasskeyEventType

    public init(eventType: PasskeyEventType) {
        self.eventType = eventType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case eventType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(eventType, forKey: .eventType)
    }
}

