//
// ConnectManageDeleteRsp.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ConnectManageDeleteRsp: Sendable, Codable, ParameterConvertible, Hashable {

    public var credentialID: String

    public init(credentialID: String) {
        self.credentialID = credentialID
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case credentialID
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(credentialID, forKey: .credentialID)
    }
}

