//
// ConnectAppendFinishRsp.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ConnectAppendFinishRsp: Sendable, Codable, ParameterConvertible, Hashable {

    public var passkeyOperation: PasskeyOperation

    public init(passkeyOperation: PasskeyOperation) {
        self.passkeyOperation = passkeyOperation
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case passkeyOperation
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(passkeyOperation, forKey: .passkeyOperation)
    }
}

