//
// ConnectLoginStartRsp.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ConnectLoginStartRsp: Sendable, Codable, ParameterConvertible, Hashable {

    public var assertionOptions: String
    public var isCDA: Bool
    public var fallbackOperationError: FallbackOperationError
    public var preferImmediatelyAvailable: Bool?

    public init(assertionOptions: String, isCDA: Bool, fallbackOperationError: FallbackOperationError, preferImmediatelyAvailable: Bool? = nil) {
        self.assertionOptions = assertionOptions
        self.isCDA = isCDA
        self.fallbackOperationError = fallbackOperationError
        self.preferImmediatelyAvailable = preferImmediatelyAvailable
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case assertionOptions
        case isCDA
        case fallbackOperationError
        case preferImmediatelyAvailable
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(assertionOptions, forKey: .assertionOptions)
        try container.encode(isCDA, forKey: .isCDA)
        try container.encode(fallbackOperationError, forKey: .fallbackOperationError)
        try container.encodeIfPresent(preferImmediatelyAvailable, forKey: .preferImmediatelyAvailable)
    }
}

