//
// ConnectManageDeleteReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ConnectManageDeleteReq: Sendable, Codable, ParameterConvertible, Hashable {

    public var connectToken: String
    public var credentialID: String

    public init(connectToken: String, credentialID: String) {
        self.connectToken = connectToken
        self.credentialID = credentialID
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case connectToken
        case credentialID
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(connectToken, forKey: .connectToken)
        try container.encode(credentialID, forKey: .credentialID)
    }
}

