//
// ConnectAppendInitReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ConnectAppendInitReq: Sendable, Codable, ParameterConvertible, Hashable {

    public var clientInformation: ClientInformation
    public var flags: [String: String]
    public var invitationToken: String?

    public init(clientInformation: ClientInformation, flags: [String: String], invitationToken: String? = nil) {
        self.clientInformation = clientInformation
        self.flags = flags
        self.invitationToken = invitationToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case clientInformation
        case flags
        case invitationToken
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(clientInformation, forKey: .clientInformation)
        try container.encode(flags, forKey: .flags)
        try container.encodeIfPresent(invitationToken, forKey: .invitationToken)
    }
}

