//
// ContinueOnOtherDevice.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ContinueOnOtherDevice: Sendable, Codable, ParameterConvertible, Hashable {

    public enum Reason: String, Sendable, Codable, CaseIterable {
        case emailLinkVerified = "email-link-verified"
        case processAlreadyCompleted = "process-already-completed"
    }
    public var reason: Reason

    public init(reason: Reason) {
        self.reason = reason
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case reason
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(reason, forKey: .reason)
    }
}

