//
// ErrorRspAllOfError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ErrorRspAllOfError: Sendable, Codable, ParameterConvertible, Hashable {

    /** Type of error */
    public var type: String
    /** Details of error */
    public var details: String?
    /** Validation errors per field */
    public var validation: [ErrorRspAllOfErrorValidation]?
    /** Additional links to help understand the error */
    public var links: [String]

    public init(type: String, details: String? = nil, validation: [ErrorRspAllOfErrorValidation]? = nil, links: [String]) {
        self.type = type
        self.details = details
        self.validation = validation
        self.links = links
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case details
        case validation
        case links
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encodeIfPresent(details, forKey: .details)
        try container.encodeIfPresent(validation, forKey: .validation)
        try container.encode(links, forKey: .links)
    }
}

