//
// FullNameWithError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FullNameWithError: Sendable, Codable, ParameterConvertible, Hashable {

    public var fullName: String
    public var error: RequestError?

    public init(fullName: String, error: RequestError? = nil) {
        self.fullName = fullName
        self.error = error
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fullName
        case error
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(fullName, forKey: .fullName)
        try container.encodeIfPresent(error, forKey: .error)
    }
}

