//
// GeneralBlockCompleted.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GeneralBlockCompleted: Sendable, Codable, ParameterConvertible, Hashable {

    public var blockType: String
    /** Only given when project environment is dev */
    public var longSession: String?
    public var shortSession: String
    public var passkeyOperation: PasskeyOperation?

    public init(blockType: String, longSession: String? = nil, shortSession: String, passkeyOperation: PasskeyOperation? = nil) {
        self.blockType = blockType
        self.longSession = longSession
        self.shortSession = shortSession
        self.passkeyOperation = passkeyOperation
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case blockType
        case longSession
        case shortSession
        case passkeyOperation
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(blockType, forKey: .blockType)
        try container.encodeIfPresent(longSession, forKey: .longSession)
        try container.encode(shortSession, forKey: .shortSession)
        try container.encodeIfPresent(passkeyOperation, forKey: .passkeyOperation)
    }
}

