//
// GeneralBlockVerifyIdentifierAlternativeVerificationMethodsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GeneralBlockVerifyIdentifierAlternativeVerificationMethodsInner: Sendable, Codable, ParameterConvertible, Hashable {

    public var verificationMethod: VerificationMethod
    public var identifier: String

    public init(verificationMethod: VerificationMethod, identifier: String) {
        self.verificationMethod = verificationMethod
        self.identifier = identifier
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case verificationMethod
        case identifier
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(verificationMethod, forKey: .verificationMethod)
        try container.encode(identifier, forKey: .identifier)
    }
}

