//
// GeneralBlockPasskeyAppended.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GeneralBlockPasskeyAppended: Sendable, Codable, ParameterConvertible, Hashable {

    public var blockType: String

    public init(blockType: String) {
        self.blockType = blockType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case blockType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(blockType, forKey: .blockType)
    }
}

