//
// GeneralBlockSignupInit.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GeneralBlockSignupInit: Sendable, Codable, ParameterConvertible, Hashable {

    public var blockType: String
    public var identifiers: [LoginIdentifierWithError]
    public var fullName: FullNameWithError?
    public var socialData: SocialData?
    public var error: RequestError?

    public init(blockType: String, identifiers: [LoginIdentifierWithError], fullName: FullNameWithError? = nil, socialData: SocialData? = nil, error: RequestError? = nil) {
        self.blockType = blockType
        self.identifiers = identifiers
        self.fullName = fullName
        self.socialData = socialData
        self.error = error
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case blockType
        case identifiers
        case fullName
        case socialData
        case error
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(blockType, forKey: .blockType)
        try container.encode(identifiers, forKey: .identifiers)
        try container.encodeIfPresent(fullName, forKey: .fullName)
        try container.encodeIfPresent(socialData, forKey: .socialData)
        try container.encodeIfPresent(error, forKey: .error)
    }
}

