//
// GeneralBlockPostSignupEmailVerify.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GeneralBlockPostSignupEmailVerify: Sendable, Codable, ParameterConvertible, Hashable {

    public var blockType: String
    public var error: RequestError?

    public init(blockType: String, error: RequestError? = nil) {
        self.blockType = blockType
        self.error = error
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case blockType
        case error
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(blockType, forKey: .blockType)
        try container.encodeIfPresent(error, forKey: .error)
    }
}

