//
// IdentifierType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Login Identifier type */
public enum IdentifierType: String, Sendable, Codable, CaseIterable {
    case email = "email"
    case phone = "phone"
    case username = "username"
}
