//
// IdentifierVerifyFinishReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct IdentifierVerifyFinishReq: Sendable, Codable, ParameterConvertible, Hashable {

    public var code: String
    public var identifierType: LoginIdentifierType
    public var verificationType: VerificationMethod
    public var isNewDevice: Bool

    public init(code: String, identifierType: LoginIdentifierType, verificationType: VerificationMethod, isNewDevice: Bool) {
        self.code = code
        self.identifierType = identifierType
        self.verificationType = verificationType
        self.isNewDevice = isNewDevice
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case identifierType
        case verificationType
        case isNewDevice
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(code, forKey: .code)
        try container.encode(identifierType, forKey: .identifierType)
        try container.encode(verificationType, forKey: .verificationType)
        try container.encode(isNewDevice, forKey: .isNewDevice)
    }
}

