//
// Identifier.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Identifier: Sendable, Codable, ParameterConvertible, Hashable {

    public var id: String
    public var value: String
    public var type: LoginIdentifierType
    public var status: String

    public init(id: String, value: String, type: LoginIdentifierType, status: String) {
        self.id = id
        self.value = value
        self.type = type
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case value
        case type
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(value, forKey: .value)
        try container.encode(type, forKey: .type)
        try container.encode(status, forKey: .status)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Identifier: Identifiable {}
