//
// IdentifierVerifyStartReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** tbd. */
public struct IdentifierVerifyStartReq: Sendable, Codable, ParameterConvertible, Hashable {

    public var identifierType: LoginIdentifierType
    public var verificationType: VerificationMethod

    public init(identifierType: LoginIdentifierType, verificationType: VerificationMethod) {
        self.identifierType = identifierType
        self.verificationType = verificationType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case identifierType
        case verificationType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(identifierType, forKey: .identifierType)
        try container.encode(verificationType, forKey: .verificationType)
    }
}

