//
// JavaScriptHighEntropy.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct JavaScriptHighEntropy: Sendable, Codable, ParameterConvertible, Hashable {

    public var platform: String
    public var platformVersion: String
    public var mobile: Bool

    public init(platform: String, platformVersion: String, mobile: Bool) {
        self.platform = platform
        self.platformVersion = platformVersion
        self.mobile = mobile
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case platform
        case platformVersion
        case mobile
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(platform, forKey: .platform)
        try container.encode(platformVersion, forKey: .platformVersion)
        try container.encode(mobile, forKey: .mobile)
    }
}

