//
// LoginIdentifierWithError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LoginIdentifierWithError: Sendable, Codable, ParameterConvertible, Hashable {

    public var type: LoginIdentifierType
    public var identifier: String
    public var error: RequestError?

    public init(type: LoginIdentifierType, identifier: String, error: RequestError? = nil) {
        self.type = type
        self.identifier = identifier
        self.error = error
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case identifier
        case error
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(identifier, forKey: .identifier)
        try container.encodeIfPresent(error, forKey: .error)
    }
}

