//
// LoginIdentifierType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum LoginIdentifierType: String, Sendable, Codable, CaseIterable {
    case email = "email"
    case phone = "phone"
    case username = "username"
}
