//
// LoginInitReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** tbd. */
public struct LoginInitReq: Sendable, Codable, ParameterConvertible, Hashable {

    public var identifierValue: String
    public var isPhone: Bool

    public init(identifierValue: String, isPhone: Bool) {
        self.identifierValue = identifierValue
        self.isPhone = isPhone
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case identifierValue
        case isPhone
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(identifierValue, forKey: .identifierValue)
        try container.encode(isPhone, forKey: .isPhone)
    }
}

