//
// LoginIdentifier.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LoginIdentifier: Sendable, Codable, ParameterConvertible, Hashable {

    public var type: LoginIdentifierType
    public var identifier: String

    public init(type: LoginIdentifierType, identifier: String) {
        self.type = type
        self.identifier = identifier
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case identifier
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(identifier, forKey: .identifier)
    }
}

