//
// MeIdentifierVerifyStartReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** tbd. */
public struct MeIdentifierVerifyStartReq: Sendable, Codable, ParameterConvertible, Hashable {

    public var identifierID: String
    public var clientInformation: ClientInformation

    public init(identifierID: String, clientInformation: ClientInformation) {
        self.identifierID = identifierID
        self.clientInformation = clientInformation
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case identifierID
        case clientInformation
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(identifierID, forKey: .identifierID)
        try container.encode(clientInformation, forKey: .clientInformation)
    }
}

