//
// MeIdentifierCreateReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MeIdentifierCreateReq: Sendable, Codable, ParameterConvertible, Hashable {

    public var identifierType: LoginIdentifierType
    public var value: String

    public init(identifierType: LoginIdentifierType, value: String) {
        self.identifierType = identifierType
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case identifierType
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(identifierType, forKey: .identifierType)
        try container.encode(value, forKey: .value)
    }
}

