//
// MeIdentifierVerifyFinishReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MeIdentifierVerifyFinishReq: Sendable, Codable, ParameterConvertible, Hashable {

    public var identifierID: String
    public var code: String

    public init(identifierID: String, code: String) {
        self.identifierID = identifierID
        self.code = code
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case identifierID
        case code
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(identifierID, forKey: .identifierID)
        try container.encode(code, forKey: .code)
    }
}

