//
// MePasskeysAppendFinishReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MePasskeysAppendFinishReq: Sendable, Codable, ParameterConvertible, Hashable {

    public var attestationResponse: String
    public var clientInformation: ClientInformation

    public init(attestationResponse: String, clientInformation: ClientInformation) {
        self.attestationResponse = attestationResponse
        self.clientInformation = clientInformation
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case attestationResponse
        case clientInformation
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(attestationResponse, forKey: .attestationResponse)
        try container.encode(clientInformation, forKey: .clientInformation)
    }
}

