//
// MePasskeysAppendStartReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MePasskeysAppendStartReq: Sendable, Codable, ParameterConvertible, Hashable {

    public var clientInformation: ClientInformation

    public init(clientInformation: ClientInformation) {
        self.clientInformation = clientInformation
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case clientInformation
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(clientInformation, forKey: .clientInformation)
    }
}

