//
// MePasskeyRsp.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MePasskeyRsp: Sendable, Codable, ParameterConvertible, Hashable {

    public var passkeys: [Passkey]
    public var paging: Paging

    public init(passkeys: [Passkey], paging: Paging) {
        self.passkeys = passkeys
        self.paging = paging
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case passkeys
        case paging
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(passkeys, forKey: .passkeys)
        try container.encode(paging, forKey: .paging)
    }
}

