//
// MeRefreshRsp.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MeRefreshRsp: Sendable, Codable, ParameterConvertible, Hashable {

    public var shortSession: String

    public init(shortSession: String) {
        self.shortSession = shortSession
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case shortSession
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(shortSession, forKey: .shortSession)
    }
}

