//
// MeRsp.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MeRsp: Sendable, Codable, ParameterConvertible, Hashable {

    public var id: String
    public var fullName: String
    public var identifiers: [Identifier]
    public var socialAccounts: [SocialAccount]

    public init(id: String, fullName: String, identifiers: [Identifier], socialAccounts: [SocialAccount]) {
        self.id = id
        self.fullName = fullName
        self.identifiers = identifiers
        self.socialAccounts = socialAccounts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case fullName
        case identifiers
        case socialAccounts
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(fullName, forKey: .fullName)
        try container.encode(identifiers, forKey: .identifiers)
        try container.encode(socialAccounts, forKey: .socialAccounts)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension MeRsp: Identifiable {}
