//
// MeUpdateReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MeUpdateReq: Sendable, Codable, ParameterConvertible, Hashable {

    public var fullName: String

    public init(fullName: String) {
        self.fullName = fullName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fullName
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(fullName, forKey: .fullName)
    }
}

