//
// NativeMetaScreen.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct NativeMetaScreen: Sendable, Codable, ParameterConvertible, Hashable {

    public var widthPoints: Float
    public var heightPoints: Float
    public var scale: Float

    public init(widthPoints: Float, heightPoints: Float, scale: Float) {
        self.widthPoints = widthPoints
        self.heightPoints = heightPoints
        self.scale = scale
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case widthPoints
        case heightPoints
        case scale
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(widthPoints, forKey: .widthPoints)
        try container.encode(heightPoints, forKey: .heightPoints)
        try container.encode(scale, forKey: .scale)
    }
}

