//
// OidcUserInfoRsp.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct OidcUserInfoRsp: Sendable, Codable, ParameterConvertible, Hashable {

    public var sub: String
    public var email: String?
    public var emailVerified: Bool?

    public init(sub: String, email: String? = nil, emailVerified: Bool? = nil) {
        self.sub = sub
        self.email = email
        self.emailVerified = emailVerified
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sub
        case email
        case emailVerified = "email_verified"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sub, forKey: .sub)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(emailVerified, forKey: .emailVerified)
    }
}

