//
// Paging.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Paging: Sendable, Codable, ParameterConvertible, Hashable {

    /** current page returned in response */
    public var page: Int = 1
    /** total number of pages available */
    public var totalPages: Int
    /** total number of items available */
    public var totalItems: Int

    public init(page: Int = 1, totalPages: Int, totalItems: Int) {
        self.page = page
        self.totalPages = totalPages
        self.totalItems = totalItems
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case page
        case totalPages
        case totalItems
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(page, forKey: .page)
        try container.encode(totalPages, forKey: .totalPages)
        try container.encode(totalItems, forKey: .totalItems)
    }
}

