//
// PasskeyIconSet.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum PasskeyIconSet: String, Sendable, Codable, CaseIterable {
    case _default = "default"
    case apple = "apple"
    case android = "android"
    case windows = "windows"
}
