//
// PasskeyMediationFinishReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** tbd. */
public struct PasskeyMediationFinishReq: Sendable, Codable, ParameterConvertible, Hashable {

    public var signedChallenge: String

    public init(signedChallenge: String) {
        self.signedChallenge = signedChallenge
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case signedChallenge
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(signedChallenge, forKey: .signedChallenge)
    }
}

