//
// ProcessStaticInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ProcessStaticInfo: Sendable, Codable, ParameterConvertible, Hashable {

    public var token: String
    public var expiresAt: Int

    public init(token: String, expiresAt: Int) {
        self.token = token
        self.expiresAt = expiresAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case token
        case expiresAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(token, forKey: .token)
        try container.encode(expiresAt, forKey: .expiresAt)
    }
}

