//
// ProcessCommon.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ProcessCommon: Sendable, Codable, ParameterConvertible, Hashable {

    public var appName: String
    public var frontendApiUrl: String
    public var hideBadge: Bool
    public var environment: String

    public init(appName: String, frontendApiUrl: String, hideBadge: Bool, environment: String) {
        self.appName = appName
        self.frontendApiUrl = frontendApiUrl
        self.hideBadge = hideBadge
        self.environment = environment
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case appName
        case frontendApiUrl
        case hideBadge
        case environment
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(appName, forKey: .appName)
        try container.encode(frontendApiUrl, forKey: .frontendApiUrl)
        try container.encode(hideBadge, forKey: .hideBadge)
        try container.encode(environment, forKey: .environment)
    }
}

