//
// ProcessInitReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** tbd. */
public struct ProcessInitReq: Sendable, Codable, ParameterConvertible, Hashable {

    public var clientInformation: ClientInformation
    public var passkeyAppendShown: Int64?
    /** deprecated */
    public var optOutOfPasskeyAppendAfterHybrid: Bool?
    public var preferredBlock: BlockType?

    public init(clientInformation: ClientInformation, passkeyAppendShown: Int64? = nil, optOutOfPasskeyAppendAfterHybrid: Bool? = nil, preferredBlock: BlockType? = nil) {
        self.clientInformation = clientInformation
        self.passkeyAppendShown = passkeyAppendShown
        self.optOutOfPasskeyAppendAfterHybrid = optOutOfPasskeyAppendAfterHybrid
        self.preferredBlock = preferredBlock
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case clientInformation
        case passkeyAppendShown
        case optOutOfPasskeyAppendAfterHybrid
        case preferredBlock
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(clientInformation, forKey: .clientInformation)
        try container.encodeIfPresent(passkeyAppendShown, forKey: .passkeyAppendShown)
        try container.encodeIfPresent(optOutOfPasskeyAppendAfterHybrid, forKey: .optOutOfPasskeyAppendAfterHybrid)
        try container.encodeIfPresent(preferredBlock, forKey: .preferredBlock)
    }
}

