//
// ProcessResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ProcessResponse: Sendable, Codable, ParameterConvertible, Hashable {

    public var blockBody: BlockBody
    public var common: ProcessCommon
    public var newProcess: ProcessStaticInfo?

    public init(blockBody: BlockBody, common: ProcessCommon, newProcess: ProcessStaticInfo? = nil) {
        self.blockBody = blockBody
        self.common = common
        self.newProcess = newProcess
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case blockBody
        case common
        case newProcess
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(blockBody, forKey: .blockBody)
        try container.encode(common, forKey: .common)
        try container.encodeIfPresent(newProcess, forKey: .newProcess)
    }
}

