//
// ProcessConfigRsp.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ProcessConfigRsp: Sendable, Codable, ParameterConvertible, Hashable {

    public var useServerSideProcessId: Bool
    public var frontendApiUrl: String

    public init(useServerSideProcessId: Bool, frontendApiUrl: String) {
        self.useServerSideProcessId = useServerSideProcessId
        self.frontendApiUrl = frontendApiUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case useServerSideProcessId
        case frontendApiUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(useServerSideProcessId, forKey: .useServerSideProcessId)
        try container.encode(frontendApiUrl, forKey: .frontendApiUrl)
    }
}

