//
// RequestData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Data about the request itself, can be used for debugging */
public struct RequestData: Sendable, Codable, ParameterConvertible, Hashable {

    /** Unique ID of request, you can provide your own while making the request, if not the ID will be randomly generated on server side */
    public var requestID: String
    /** Link to dashboard with details about request */
    public var link: String

    public init(requestID: String, link: String) {
        self.requestID = requestID
        self.link = link
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case requestID
        case link
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(requestID, forKey: .requestID)
        try container.encode(link, forKey: .link)
    }
}

