//
// SessionManagement.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** What session management should be used */
public enum SessionManagement: String, Sendable, Codable, CaseIterable {
    case sessionManagementCorbado = "SessionManagementCorbado"
    case sessionManagementOwn = "SessionManagementOwn"
}
