//
// SessionConfigRsp.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SessionConfigRsp: Sendable, Codable, ParameterConvertible, Hashable {

    public var useSessionManagement: Bool
    public var shortSessionCookieConfig: ShortSessionCookieConfig?
    public var frontendApiUrl: String?

    public init(useSessionManagement: Bool, shortSessionCookieConfig: ShortSessionCookieConfig? = nil, frontendApiUrl: String? = nil) {
        self.useSessionManagement = useSessionManagement
        self.shortSessionCookieConfig = shortSessionCookieConfig
        self.frontendApiUrl = frontendApiUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case useSessionManagement
        case shortSessionCookieConfig
        case frontendApiUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(useSessionManagement, forKey: .useSessionManagement)
        try container.encodeIfPresent(shortSessionCookieConfig, forKey: .shortSessionCookieConfig)
        try container.encodeIfPresent(frontendApiUrl, forKey: .frontendApiUrl)
    }
}

