//
// SignupInitReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** tbd. */
public struct SignupInitReq: Sendable, Codable, ParameterConvertible, Hashable {

    public var fullName: String?
    public var identifiers: [LoginIdentifier]

    public init(fullName: String? = nil, identifiers: [LoginIdentifier]) {
        self.fullName = fullName
        self.identifiers = identifiers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fullName
        case identifiers
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(fullName, forKey: .fullName)
        try container.encode(identifiers, forKey: .identifiers)
    }
}

