//
// SocialVerifyStartReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SocialVerifyStartReq: Sendable, Codable, ParameterConvertible, Hashable {

    public var providerType: SocialProviderType
    public var redirectUrl: String
    public var authType: AuthType

    public init(providerType: SocialProviderType, redirectUrl: String, authType: AuthType) {
        self.providerType = providerType
        self.redirectUrl = redirectUrl
        self.authType = authType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case providerType
        case redirectUrl
        case authType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(providerType, forKey: .providerType)
        try container.encode(redirectUrl, forKey: .redirectUrl)
        try container.encode(authType, forKey: .authType)
    }
}

