//
// SocialData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SocialData: Sendable, Codable, ParameterConvertible, Hashable {

    public enum Status: String, Sendable, Codable, CaseIterable {
        case initial = "initial"
        case started = "started"
        case finished = "finished"
    }
    public var providers: [SocialProviderType]
    public var status: Status
    public var oauthUrl: String?
    public var error: RequestError?

    public init(providers: [SocialProviderType], status: Status, oauthUrl: String? = nil, error: RequestError? = nil) {
        self.providers = providers
        self.status = status
        self.oauthUrl = oauthUrl
        self.error = error
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case providers
        case status
        case oauthUrl
        case error
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(providers, forKey: .providers)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(oauthUrl, forKey: .oauthUrl)
        try container.encodeIfPresent(error, forKey: .error)
    }
}

