//
// SocialProviderType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum SocialProviderType: String, Sendable, Codable, CaseIterable {
    case google = "google"
    case microsoft = "microsoft"
    case github = "github"
}
