//
// Status.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Generic status that can describe Corbado entities */
public enum Status: String, Sendable, Codable, CaseIterable {
    case active = "active"
    case pending = "pending"
    case deleted = "deleted"
}
