//
// UserDetailsConfigRsp.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UserDetailsConfigRsp: Sendable, Codable, ParameterConvertible, Hashable {

    public var fullNameRequired: Bool
    public var identifiers: [LoginIdentifierConfig]

    public init(fullNameRequired: Bool, identifiers: [LoginIdentifierConfig]) {
        self.fullNameRequired = fullNameRequired
        self.identifiers = identifiers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fullNameRequired
        case identifiers
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(fullNameRequired, forKey: .fullNameRequired)
        try container.encode(identifiers, forKey: .identifiers)
    }
}

