//
// UserUsername.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** User&#39;s username */
public struct UserUsername: Sendable, Codable, ParameterConvertible, Hashable {

    /** generic ID */
    public var ID: String
    public var username: String
    /** Timestamp of when the entity was created in yyyy-MM-dd'T'HH:mm:ss format */
    public var created: String
    /** Timestamp of when the entity was last updated in yyyy-MM-dd'T'HH:mm:ss format */
    public var updated: String
    public var status: Status

    public init(ID: String, username: String, created: String, updated: String, status: Status) {
        self.ID = ID
        self.username = username
        self.created = created
        self.updated = updated
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ID
        case username
        case created
        case updated
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ID, forKey: .ID)
        try container.encode(username, forKey: .username)
        try container.encode(created, forKey: .created)
        try container.encode(updated, forKey: .updated)
        try container.encode(status, forKey: .status)
    }
}

