//
// VerificationMethod.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum VerificationMethod: String, Sendable, Codable, CaseIterable {
    case emailLink = "email-link"
    case emailOtp = "email-otp"
    case phoneOtp = "phone-otp"
}
