//
// AuthAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class AuthAPI {

    /**
     Skip Authentication Block
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ProcessResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func blockSkip(apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> ProcessResponse {
        return try await blockSkipWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Skip Authentication Block
     - POST /v2/auth/block/skip
     - Skips the current authentication block
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - API Key:
       - type: apiKey X-Corbado-ProjectID (HEADER)
       - name: projectID
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ProcessResponse> 
     */
    open class func blockSkipWithRequestBuilder(apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<ProcessResponse> {
        let localVariablePath = "/v2/auth/block/skip"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ProcessResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Create Authentication Event
     
     - parameter eventCreateReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func eventCreate(eventCreateReq: EventCreateReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await eventCreateWithRequestBuilder(eventCreateReq: eventCreateReq, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create Authentication Event
     - POST /v2/auth/events
     - Creates a new user generated complete event
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - API Key:
       - type: apiKey X-Corbado-ProjectID (HEADER)
       - name: projectID
     - parameter eventCreateReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func eventCreateWithRequestBuilder(eventCreateReq: EventCreateReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        let localVariablePath = "/v2/auth/events"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: eventCreateReq, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Update Identifier
     
     - parameter identifierUpdateReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ProcessResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func identifierUpdate(identifierUpdateReq: IdentifierUpdateReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> ProcessResponse {
        return try await identifierUpdateWithRequestBuilder(identifierUpdateReq: identifierUpdateReq, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Update Identifier
     - POST /v2/auth/identifier/update
     - Updates the user's identifier information
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - API Key:
       - type: apiKey X-Corbado-ProjectID (HEADER)
       - name: projectID
     - parameter identifierUpdateReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ProcessResponse> 
     */
    open class func identifierUpdateWithRequestBuilder(identifierUpdateReq: IdentifierUpdateReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<ProcessResponse> {
        let localVariablePath = "/v2/auth/identifier/update"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: identifierUpdateReq, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ProcessResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Finish Identifier Verification
     
     - parameter identifierVerifyFinishReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ProcessResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func identifierVerifyFinish(identifierVerifyFinishReq: IdentifierVerifyFinishReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> ProcessResponse {
        return try await identifierVerifyFinishWithRequestBuilder(identifierVerifyFinishReq: identifierVerifyFinishReq, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Finish Identifier Verification
     - POST /v2/auth/identifier/verify/finish
     - Completes the identifier verification process
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - API Key:
       - type: apiKey X-Corbado-ProjectID (HEADER)
       - name: projectID
     - parameter identifierVerifyFinishReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ProcessResponse> 
     */
    open class func identifierVerifyFinishWithRequestBuilder(identifierVerifyFinishReq: IdentifierVerifyFinishReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<ProcessResponse> {
        let localVariablePath = "/v2/auth/identifier/verify/finish"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: identifierVerifyFinishReq, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ProcessResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Start Identifier Verification
     
     - parameter identifierVerifyStartReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ProcessResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func identifierVerifyStart(identifierVerifyStartReq: IdentifierVerifyStartReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> ProcessResponse {
        return try await identifierVerifyStartWithRequestBuilder(identifierVerifyStartReq: identifierVerifyStartReq, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Start Identifier Verification
     - POST /v2/auth/identifier/verify/start
     - Initiates the identifier verification process
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - API Key:
       - type: apiKey X-Corbado-ProjectID (HEADER)
       - name: projectID
     - parameter identifierVerifyStartReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ProcessResponse> 
     */
    open class func identifierVerifyStartWithRequestBuilder(identifierVerifyStartReq: IdentifierVerifyStartReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<ProcessResponse> {
        let localVariablePath = "/v2/auth/identifier/verify/start"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: identifierVerifyStartReq, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ProcessResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get Identifier Verification Status
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ProcessResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func identifierVerifyStatus(apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> ProcessResponse {
        return try await identifierVerifyStatusWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get Identifier Verification Status
     - GET /v2/auth/identifier/verify/status
     - Retrieves the current status of identifier verification
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - API Key:
       - type: apiKey X-Corbado-ProjectID (HEADER)
       - name: projectID
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ProcessResponse> 
     */
    open class func identifierVerifyStatusWithRequestBuilder(apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<ProcessResponse> {
        let localVariablePath = "/v2/auth/identifier/verify/status"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ProcessResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Initialize Login
     
     - parameter loginInitReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ProcessResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func loginInit(loginInitReq: LoginInitReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> ProcessResponse {
        return try await loginInitWithRequestBuilder(loginInitReq: loginInitReq, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Initialize Login
     - POST /v2/auth/login/init
     - Initializes a new login process
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - API Key:
       - type: apiKey X-Corbado-ProjectID (HEADER)
       - name: projectID
     - parameter loginInitReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ProcessResponse> 
     */
    open class func loginInitWithRequestBuilder(loginInitReq: LoginInitReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<ProcessResponse> {
        let localVariablePath = "/v2/auth/login/init"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: loginInitReq, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ProcessResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Finish Passkey Append
     
     - parameter passkeyAppendFinishReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ProcessResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func passkeyAppendFinish(passkeyAppendFinishReq: PasskeyAppendFinishReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> ProcessResponse {
        return try await passkeyAppendFinishWithRequestBuilder(passkeyAppendFinishReq: passkeyAppendFinishReq, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Finish Passkey Append
     - POST /v2/auth/passkey/append/finish
     - Completes the process of appending a new passkey
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - API Key:
       - type: apiKey X-Corbado-ProjectID (HEADER)
       - name: projectID
     - parameter passkeyAppendFinishReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ProcessResponse> 
     */
    open class func passkeyAppendFinishWithRequestBuilder(passkeyAppendFinishReq: PasskeyAppendFinishReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<ProcessResponse> {
        let localVariablePath = "/v2/auth/passkey/append/finish"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: passkeyAppendFinishReq, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ProcessResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Start Passkey Append
     
     - parameter passkeyAppendStartReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ProcessResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func passkeyAppendStart(passkeyAppendStartReq: PasskeyAppendStartReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> ProcessResponse {
        return try await passkeyAppendStartWithRequestBuilder(passkeyAppendStartReq: passkeyAppendStartReq, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Start Passkey Append
     - POST /v2/auth/passkey/append/start
     - Starts the process of appending a new passkey
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - API Key:
       - type: apiKey X-Corbado-ProjectID (HEADER)
       - name: projectID
     - parameter passkeyAppendStartReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ProcessResponse> 
     */
    open class func passkeyAppendStartWithRequestBuilder(passkeyAppendStartReq: PasskeyAppendStartReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<ProcessResponse> {
        let localVariablePath = "/v2/auth/passkey/append/start"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: passkeyAppendStartReq, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ProcessResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Finish Passkey Login
     
     - parameter passkeyLoginFinishReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ProcessResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func passkeyLoginFinish(passkeyLoginFinishReq: PasskeyLoginFinishReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> ProcessResponse {
        return try await passkeyLoginFinishWithRequestBuilder(passkeyLoginFinishReq: passkeyLoginFinishReq, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Finish Passkey Login
     - POST /v2/auth/passkey/login/finish
     - Completes the passkey login process
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - API Key:
       - type: apiKey X-Corbado-ProjectID (HEADER)
       - name: projectID
     - parameter passkeyLoginFinishReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ProcessResponse> 
     */
    open class func passkeyLoginFinishWithRequestBuilder(passkeyLoginFinishReq: PasskeyLoginFinishReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<ProcessResponse> {
        let localVariablePath = "/v2/auth/passkey/login/finish"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: passkeyLoginFinishReq, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ProcessResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Start Passkey Login
     
     - parameter passkeyLoginStartReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ProcessResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func passkeyLoginStart(passkeyLoginStartReq: PasskeyLoginStartReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> ProcessResponse {
        return try await passkeyLoginStartWithRequestBuilder(passkeyLoginStartReq: passkeyLoginStartReq, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Start Passkey Login
     - POST /v2/auth/passkey/login/start
     - Initiates the passkey login process
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - API Key:
       - type: apiKey X-Corbado-ProjectID (HEADER)
       - name: projectID
     - parameter passkeyLoginStartReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ProcessResponse> 
     */
    open class func passkeyLoginStartWithRequestBuilder(passkeyLoginStartReq: PasskeyLoginStartReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<ProcessResponse> {
        let localVariablePath = "/v2/auth/passkey/login/start"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: passkeyLoginStartReq, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ProcessResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Finish Passkey Mediation
     
     - parameter passkeyMediationFinishReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ProcessResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func passkeyMediationFinish(passkeyMediationFinishReq: PasskeyMediationFinishReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> ProcessResponse {
        return try await passkeyMediationFinishWithRequestBuilder(passkeyMediationFinishReq: passkeyMediationFinishReq, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Finish Passkey Mediation
     - POST /v2/auth/passkey/mediation/finish
     - Completes the passkey mediation process
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - API Key:
       - type: apiKey X-Corbado-ProjectID (HEADER)
       - name: projectID
     - parameter passkeyMediationFinishReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ProcessResponse> 
     */
    open class func passkeyMediationFinishWithRequestBuilder(passkeyMediationFinishReq: PasskeyMediationFinishReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<ProcessResponse> {
        let localVariablePath = "/v2/auth/passkey/mediation/finish"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: passkeyMediationFinishReq, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ProcessResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Complete Authentication Process
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ProcessResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func processComplete(apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> ProcessResponse {
        return try await processCompleteWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Complete Authentication Process
     - POST /v2/auth/process/complete
     - Completes the current authentication process
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - API Key:
       - type: apiKey X-Corbado-ProjectID (HEADER)
       - name: projectID
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ProcessResponse> 
     */
    open class func processCompleteWithRequestBuilder(apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<ProcessResponse> {
        let localVariablePath = "/v2/auth/process/complete"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ProcessResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get Authentication Process
     
     - parameter preferredBlock: (query)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ProcessResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func processGet(preferredBlock: BlockType? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> ProcessResponse {
        return try await processGetWithRequestBuilder(preferredBlock: preferredBlock, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get Authentication Process
     - GET /v2/auth/process
     - Retrieves the current authentication process state
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - API Key:
       - type: apiKey X-Corbado-ProjectID (HEADER)
       - name: projectID
     - parameter preferredBlock: (query)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ProcessResponse> 
     */
    open class func processGetWithRequestBuilder(preferredBlock: BlockType? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<ProcessResponse> {
        let localVariablePath = "/v2/auth/process"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "preferredBlock": (wrappedValue: preferredBlock?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ProcessResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Initialize Authentication Process
     
     - parameter processInitReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ProcessInitRsp
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func processInit(processInitReq: ProcessInitReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> ProcessInitRsp {
        return try await processInitWithRequestBuilder(processInitReq: processInitReq, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Initialize Authentication Process
     - POST /v2/auth/process/init
     - Initializes a new authentication process
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - API Key:
       - type: apiKey X-Corbado-ProjectID (HEADER)
       - name: projectID
     - parameter processInitReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ProcessInitRsp> 
     */
    open class func processInitWithRequestBuilder(processInitReq: ProcessInitReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<ProcessInitRsp> {
        let localVariablePath = "/v2/auth/process/init"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: processInitReq, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ProcessInitRsp>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Reset Authentication Process
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ProcessResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func processReset(apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> ProcessResponse {
        return try await processResetWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Reset Authentication Process
     - POST /v2/auth/process/reset
     - Resets the current authentication process
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - API Key:
       - type: apiKey X-Corbado-ProjectID (HEADER)
       - name: projectID
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ProcessResponse> 
     */
    open class func processResetWithRequestBuilder(apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<ProcessResponse> {
        let localVariablePath = "/v2/auth/process/reset"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ProcessResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Initialize Signup
     
     - parameter signupInitReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ProcessResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func signupInit(signupInitReq: SignupInitReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> ProcessResponse {
        return try await signupInitWithRequestBuilder(signupInitReq: signupInitReq, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Initialize Signup
     - POST /v2/auth/signup/init
     - Initializes a new user signup process
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - API Key:
       - type: apiKey X-Corbado-ProjectID (HEADER)
       - name: projectID
     - parameter signupInitReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ProcessResponse> 
     */
    open class func signupInitWithRequestBuilder(signupInitReq: SignupInitReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<ProcessResponse> {
        let localVariablePath = "/v2/auth/signup/init"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: signupInitReq, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ProcessResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Social Verification Callback
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func socialVerifyCallback(apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await socialVerifyCallbackWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Social Verification Callback
     - GET /v2/auth/social/verify/callback
     - Handles the callback from social authentication providers
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - API Key:
       - type: apiKey X-Corbado-ProjectID (HEADER)
       - name: projectID
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func socialVerifyCallbackWithRequestBuilder(apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        let localVariablePath = "/v2/auth/social/verify/callback"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Finish Social Verification
     
     - parameter body: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ProcessResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func socialVerifyFinish(body: JSONValue, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> ProcessResponse {
        return try await socialVerifyFinishWithRequestBuilder(body: body, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Finish Social Verification
     - POST /v2/auth/social/verify/finish
     - Completes the social authentication verification process
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - API Key:
       - type: apiKey X-Corbado-ProjectID (HEADER)
       - name: projectID
     - parameter body: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ProcessResponse> 
     */
    open class func socialVerifyFinishWithRequestBuilder(body: JSONValue, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<ProcessResponse> {
        let localVariablePath = "/v2/auth/social/verify/finish"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ProcessResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Start Social Verification
     
     - parameter socialVerifyStartReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ProcessResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func socialVerifyStart(socialVerifyStartReq: SocialVerifyStartReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> ProcessResponse {
        return try await socialVerifyStartWithRequestBuilder(socialVerifyStartReq: socialVerifyStartReq, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Start Social Verification
     - POST /v2/auth/social/verify/start
     - Initiates the social authentication verification process
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - API Key:
       - type: apiKey X-Corbado-ProjectID (HEADER)
       - name: projectID
     - parameter socialVerifyStartReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ProcessResponse> 
     */
    open class func socialVerifyStartWithRequestBuilder(socialVerifyStartReq: SocialVerifyStartReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<ProcessResponse> {
        let localVariablePath = "/v2/auth/social/verify/start"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: socialVerifyStartReq, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ProcessResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
