//
// UsersAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class UsersAPI {

    /**
     Delete current user
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: GenericRsp
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func currentUserDelete(apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> GenericRsp {
        return try await currentUserDeleteWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delete current user
     - DELETE /v2/me
     - Deletes currently logged in user. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - API Key:
       - type: apiKey X-Corbado-ProjectID (HEADER)
       - name: projectID
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<GenericRsp> 
     */
    open class func currentUserDeleteWithRequestBuilder(apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<GenericRsp> {
        let localVariablePath = "/v2/me"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GenericRsp>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Retrieve current user
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: MeRsp
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func currentUserGet(apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> MeRsp {
        return try await currentUserGetWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Retrieve current user
     - GET /v2/me
     - Retrieves data of currently logged in user including their [login identifiers](/api-reference/backend-api/loginidentifiers/create-a-login-identifier-for-a-user) and [social logins](/api-reference/backend-api/users/create-a-social-login-for-a-user). 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - API Key:
       - type: apiKey X-Corbado-ProjectID (HEADER)
       - name: projectID
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<MeRsp> 
     */
    open class func currentUserGetWithRequestBuilder(apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<MeRsp> {
        let localVariablePath = "/v2/me"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MeRsp>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Create login identifier
     
     - parameter meIdentifierCreateReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: GenericRsp
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func currentUserIdentifierCreate(meIdentifierCreateReq: MeIdentifierCreateReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> GenericRsp {
        return try await currentUserIdentifierCreateWithRequestBuilder(meIdentifierCreateReq: meIdentifierCreateReq, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create login identifier
     - POST /v2/me/identifier
     - Creates a login identifier for the currently logged in user. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - API Key:
       - type: apiKey X-Corbado-ProjectID (HEADER)
       - name: projectID
     - parameter meIdentifierCreateReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<GenericRsp> 
     */
    open class func currentUserIdentifierCreateWithRequestBuilder(meIdentifierCreateReq: MeIdentifierCreateReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<GenericRsp> {
        let localVariablePath = "/v2/me/identifier"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: meIdentifierCreateReq, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GenericRsp>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Delete login identifier
     
     - parameter meIdentifierDeleteReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: GenericRsp
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func currentUserIdentifierDelete(meIdentifierDeleteReq: MeIdentifierDeleteReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> GenericRsp {
        return try await currentUserIdentifierDeleteWithRequestBuilder(meIdentifierDeleteReq: meIdentifierDeleteReq, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delete login identifier
     - DELETE /v2/me/identifier
     - Deletes a login identifier for the currently logged in user. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - API Key:
       - type: apiKey X-Corbado-ProjectID (HEADER)
       - name: projectID
     - parameter meIdentifierDeleteReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<GenericRsp> 
     */
    open class func currentUserIdentifierDeleteWithRequestBuilder(meIdentifierDeleteReq: MeIdentifierDeleteReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<GenericRsp> {
        let localVariablePath = "/v2/me/identifier"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: meIdentifierDeleteReq, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GenericRsp>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Update login identifier
     
     - parameter meIdentifierUpdateReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: GenericRsp
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func currentUserIdentifierUpdate(meIdentifierUpdateReq: MeIdentifierUpdateReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> GenericRsp {
        return try await currentUserIdentifierUpdateWithRequestBuilder(meIdentifierUpdateReq: meIdentifierUpdateReq, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Update login identifier
     - PATCH /v2/me/identifier
     - Updates a login identifier for the currently logged in user. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - API Key:
       - type: apiKey X-Corbado-ProjectID (HEADER)
       - name: projectID
     - parameter meIdentifierUpdateReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<GenericRsp> 
     */
    open class func currentUserIdentifierUpdateWithRequestBuilder(meIdentifierUpdateReq: MeIdentifierUpdateReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<GenericRsp> {
        let localVariablePath = "/v2/me/identifier"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: meIdentifierUpdateReq, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GenericRsp>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Finish login identifier verification
     
     - parameter meIdentifierVerifyFinishReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: GenericRsp
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func currentUserIdentifierVerifyFinish(meIdentifierVerifyFinishReq: MeIdentifierVerifyFinishReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> GenericRsp {
        return try await currentUserIdentifierVerifyFinishWithRequestBuilder(meIdentifierVerifyFinishReq: meIdentifierVerifyFinishReq, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Finish login identifier verification
     - POST /v2/me/identifier/verify/finish
     - Finishes login identifer verification of currently logged in user. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - API Key:
       - type: apiKey X-Corbado-ProjectID (HEADER)
       - name: projectID
     - parameter meIdentifierVerifyFinishReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<GenericRsp> 
     */
    open class func currentUserIdentifierVerifyFinishWithRequestBuilder(meIdentifierVerifyFinishReq: MeIdentifierVerifyFinishReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<GenericRsp> {
        let localVariablePath = "/v2/me/identifier/verify/finish"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: meIdentifierVerifyFinishReq, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GenericRsp>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Start login identifier verification
     
     - parameter meIdentifierVerifyStartReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: GenericRsp
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func currentUserIdentifierVerifyStart(meIdentifierVerifyStartReq: MeIdentifierVerifyStartReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> GenericRsp {
        return try await currentUserIdentifierVerifyStartWithRequestBuilder(meIdentifierVerifyStartReq: meIdentifierVerifyStartReq, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Start login identifier verification
     - POST /v2/me/identifier/verify/start
     - Starts login identifer verification of currently logged in user. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - API Key:
       - type: apiKey X-Corbado-ProjectID (HEADER)
       - name: projectID
     - parameter meIdentifierVerifyStartReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<GenericRsp> 
     */
    open class func currentUserIdentifierVerifyStartWithRequestBuilder(meIdentifierVerifyStartReq: MeIdentifierVerifyStartReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<GenericRsp> {
        let localVariablePath = "/v2/me/identifier/verify/start"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: meIdentifierVerifyStartReq, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GenericRsp>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Finish passkey append
     
     - parameter mePasskeysAppendFinishReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func currentUserPasskeyAppendFinish(mePasskeysAppendFinishReq: MePasskeysAppendFinishReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await currentUserPasskeyAppendFinishWithRequestBuilder(mePasskeysAppendFinishReq: mePasskeysAppendFinishReq, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Finish passkey append
     - POST /v2/me/passkeys/append/finish
     - Finishes passkey append for currently logged in user. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - API Key:
       - type: apiKey X-Corbado-ProjectID (HEADER)
       - name: projectID
     - parameter mePasskeysAppendFinishReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func currentUserPasskeyAppendFinishWithRequestBuilder(mePasskeysAppendFinishReq: MePasskeysAppendFinishReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        let localVariablePath = "/v2/me/passkeys/append/finish"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: mePasskeysAppendFinishReq, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Start passkey append
     
     - parameter mePasskeysAppendStartReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: MePasskeysAppendStartRsp
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func currentUserPasskeyAppendStart(mePasskeysAppendStartReq: MePasskeysAppendStartReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> MePasskeysAppendStartRsp {
        return try await currentUserPasskeyAppendStartWithRequestBuilder(mePasskeysAppendStartReq: mePasskeysAppendStartReq, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Start passkey append
     - POST /v2/me/passkeys/append/start
     - Starts passkey append for currently logged in user. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - API Key:
       - type: apiKey X-Corbado-ProjectID (HEADER)
       - name: projectID
     - parameter mePasskeysAppendStartReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<MePasskeysAppendStartRsp> 
     */
    open class func currentUserPasskeyAppendStartWithRequestBuilder(mePasskeysAppendStartReq: MePasskeysAppendStartReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<MePasskeysAppendStartRsp> {
        let localVariablePath = "/v2/me/passkeys/append/start"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: mePasskeysAppendStartReq, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MePasskeysAppendStartRsp>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Delete user passkey
     
     - parameter credentialID: (path) Unique identifier of the passkey. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: MePasskeyDeleteRsp
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func currentUserPasskeyDelete(credentialID: String, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> MePasskeyDeleteRsp {
        return try await currentUserPasskeyDeleteWithRequestBuilder(credentialID: credentialID, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delete user passkey
     - DELETE /v2/me/passkeys/{credentialID}
     - Deletes a passkey for the currently logged in user. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - API Key:
       - type: apiKey X-Corbado-ProjectID (HEADER)
       - name: projectID
     - parameter credentialID: (path) Unique identifier of the passkey. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<MePasskeyDeleteRsp> 
     */
    open class func currentUserPasskeyDeleteWithRequestBuilder(credentialID: String, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<MePasskeyDeleteRsp> {
        var localVariablePath = "/v2/me/passkeys/{credentialID}"
        let credentialIDPreEscape = "\(APIHelper.mapValueToPathItem(credentialID))"
        let credentialIDPostEscape = credentialIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{credentialID}", with: credentialIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MePasskeyDeleteRsp>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List all user passkeys
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: MePasskeyRsp
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func currentUserPasskeyGet(apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> MePasskeyRsp {
        return try await currentUserPasskeyGetWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List all user passkeys
     - GET /v2/me/passkeys
     - Returns a list of passkeys for the currently logged in user. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - API Key:
       - type: apiKey X-Corbado-ProjectID (HEADER)
       - name: projectID
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<MePasskeyRsp> 
     */
    open class func currentUserPasskeyGetWithRequestBuilder(apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<MePasskeyRsp> {
        let localVariablePath = "/v2/me/passkeys"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MePasskeyRsp>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Logout user
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func currentUserSessionLogout(apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await currentUserSessionLogoutWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Logout user
     - POST /v2/me/logout
     - Performs session logout of currently logged in user.  Manage users sessions in the [Developer Panel](https://app.corbado.com/users/sessions) or consult the [Documentation](https://docs.corbado.com/corbado-complete/sessions/overview) for more details. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - API Key:
       - type: apiKey X-Corbado-ProjectID (HEADER)
       - name: projectID
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func currentUserSessionLogoutWithRequestBuilder(apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        let localVariablePath = "/v2/me/logout"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Refresh user session
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: MeRefreshRsp
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func currentUserSessionRefresh(apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> MeRefreshRsp {
        return try await currentUserSessionRefreshWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Refresh user session
     - POST /v2/me/refresh
     - Performs session refresh of currently logged in user. Issues a new session-token if session is still valid.  Manage users sessions in the [Developer Panel](https://app.corbado.com/users/sessions) or consult the [Documentation](https://docs.corbado.com/corbado-complete/sessions/overview) for more details. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - API Key:
       - type: apiKey X-Corbado-ProjectID (HEADER)
       - name: projectID
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<MeRefreshRsp> 
     */
    open class func currentUserSessionRefreshWithRequestBuilder(apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<MeRefreshRsp> {
        let localVariablePath = "/v2/me/refresh"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MeRefreshRsp>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Update current User
     
     - parameter meUpdateReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: GenericRsp
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func currentUserUpdate(meUpdateReq: MeUpdateReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> GenericRsp {
        return try await currentUserUpdateWithRequestBuilder(meUpdateReq: meUpdateReq, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Update current User
     - PATCH /v2/me
     - Updates data of currently logged in user. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - API Key:
       - type: apiKey X-Corbado-ProjectID (HEADER)
       - name: projectID
     - parameter meUpdateReq: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<GenericRsp> 
     */
    open class func currentUserUpdateWithRequestBuilder(meUpdateReq: MeUpdateReq, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<GenericRsp> {
        let localVariablePath = "/v2/me"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: meUpdateReq, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GenericRsp>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
