name: Swift CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sdk_tests:
    runs-on: macos-15
    name: SDK Tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode 26.0.1
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '26.0.1'

      - name: Run SDK tests
        run: xcodebuild test -scheme CorbadoConnect -destination 'platform=iOS Simulator,name=iPhone 17,OS=26.0'
